Changed 'exit 1' to be a TODO item

diff --git a/.github/workflows/aws-eks-verify.yml b/.github/workflows/aws-eks-verify.yml
--- a/.github/workflows/aws-eks-verify.yml
+++ b/.github/workflows/aws-eks-verify.yml
@@ -101,4 +101,4 @@ jobs:
         run: |
           echo Probr did not successfully validate the EKS cluster.
           echo Please review the Probr artifact for detailed information.
-          exit 1
+        # TODO: Add 'exit 1' for failures
